#10 Fix application build breakage due to Unity validating test assembly
Even if the `mrwatts.fuelinject.testing` assembly is not used anywhere,
Unity will still validate it during build, causing a failure along the
following lines:

```
ArgumentException: The Assembly UnityEngine.TestRunner is referenced by
 mrwatts.fuelinject.testing ('Library/PlayerScriptAssemblies/
 mrwatts.fuelinject.testing.dll'). But the dll is not allowed to be
 included or could not be found.
```

This fixes that by adding the constraint UNITY_INCLUDE_TESTS. Strictly
speaking this is not correct since this assembly does not contain tests
(which is what this is used for [1]), but only test utility code, but
Unity apparently needs this to ignore the code during regular builds.

(Trying to limit the assembly to just the editor probably wouldn't be
correct, since Unity can make special builds that run tests on-device.)

[1] https://forum.unity.com/threads/info-on-unity_include_tests-define.890095/#post-5933573